const API_BASE = "https://ss-store-api-production.up.railway.app";
const CART_KEY = "ss-store-cart";
const PHONE_KEY = "ss-store-phone";
const LAST_ORDER_KEY = "ss-store-last-order";
const page = document.body.dataset.page;
const $ = (selector, root = document) => root.querySelector(selector);
const money = (value) => `₹${Number(value || 0).toLocaleString("en-IN")}`;
const esc = (value) => String(value ?? "").replace(/[&<>'"]/g, (char) => ({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[char]));
const state = { products: [], categories: [], cart: readCart(), category: "all", search: "", loading: false, submitting: false };
function readCart(){ try { return JSON.parse(localStorage.getItem(CART_KEY) || "{}"); } catch { return {}; } }
function writeCart(){ localStorage.setItem(CART_KEY, JSON.stringify(state.cart)); }
function cartCount(){ return Object.values(state.cart).reduce((sum, qty) => sum + Number(qty), 0); }
function cartItems(){ return Object.entries(state.cart).map(([id, quantity]) => { const product = state.products.find((item) => Number(item.id) === Number(id)); return product ? { product, quantity:Number(quantity) } : null; }).filter(Boolean); }
function cartTotal(){ return cartItems().reduce((sum, item) => sum + Number(item.product.price) * item.quantity, 0); }
function toast(message, type = "success"){ const stack = $("#toast-stack"); if (!stack) return; const node = document.createElement("div"); node.className = `toast ${type}`; node.textContent = message; stack.append(node); setTimeout(() => node.remove(), 4200); }
function formatStatus(status){ return String(status || "PENDING").replaceAll("_", " ").toLowerCase().replace(/\b\w/g, (letter) => letter.toUpperCase()); }
function apiError(message, status = 0, details = null){ return Object.assign(new Error(message), { status, details }); }
async function request(path, options = {}){ const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), options.timeoutMs || 12000); try { const response = await fetch(`${API_BASE}${path}`, { ...options, signal:controller.signal, headers:{ Accept:"application/json", "Content-Type":"application/json", ...(options.headers || {}) } }); const body = await response.json().catch(() => null); if (!response.ok || body?.success === false) throw apiError(body?.message || `Request failed (${response.status})`, response.status, body?.details); return body?.data; } catch(error){ if(error.name === "AbortError") throw apiError("The request timed out. Try again."); if(error instanceof Error && error.message) throw error; throw apiError("Network error. Check your connection and try again."); } finally { clearTimeout(timer); } }
async function fetchProducts(){ const data = await request("/api/products?take=100"); state.products = (Array.isArray(data) ? data : data?.items || []).map((product) => ({ ...product, categoryName:product.category?.name || "Essentials" })); }
async function fetchCategories(){ const data = await request("/api/categories"); state.categories = (Array.isArray(data) ? data : data?.items || []).filter((item) => item?.name); }
async function fetchCatalog(){ state.loading = true; render(); try { await Promise.all([fetchProducts(), fetchCategories()]); } catch(error){ state.error = error.message; toast(error.message, "error"); } finally { state.loading = false; render(); } }
function imageMarkup(product){ const src = product.imageUrl || product.image; return src ? `<img src="${esc(src)}" alt="${esc(product.name)}" loading="lazy" onerror="this.style.display='none';this.nextElementSibling.style.display='block'" /><span class="placeholder-image" style="display:none">📦</span>` : `<span class="placeholder-image">📦</span>`; }
function header(){ return `<header class="topbar"><div class="topbar-inner"><div class="brand-row"><a class="brand" href="index.html"><span class="brand-mark">SS</span><span><strong>SS Store</strong><small>fresh in a flash</small></span></a><a class="cart-icon" href="cart.html" aria-label="View cart">🛍<span class="cart-count" id="cart-count">${cartCount()}</span></a></div><div class="location-row"><button class="location-button">⌖ Deliver to Indiranagar, Bengaluru</button><span class="delivery-note">⚡ 10 min delivery</span></div><label class="search-wrap"><span>⌕</span><input class="search-input" id="search-input" placeholder="Search groceries, soap, coffee..." value="${esc(state.search)}"></label></div></header>`; }
function bottomNav(){ return `<nav class="bottom-nav"><a href="index.html" class="${page === "home" ? "active" : ""}"><span>⌂</span>Home</a><a href="index.html#categories" class="${page === "home" ? "" : ""}"><span>⌑</span>Categories</a><a href="cart.html" class="${page === "cart" ? "active" : ""}"><span>🛍</span>Cart</a></nav>`; }
function appShell(content){ return `<div class="app">${header()}${content}${bottomNav()}<div class="toast-stack" id="toast-stack"></div></div>`; }
function productCard(product){ const quantity = Number(state.cart[product.id] || 0); const out = Number(product.stock) <= 0; return `<article class="product-card"><div class="product-image"><span class="product-badge">${out ? "Sold out" : Number(product.stock) < 10 ? "Low stock" : "SS pick"}</span>${imageMarkup(product)}</div><h3>${esc(product.name)}</h3><p class="detail">${esc(product.categoryName)} · ${Number(product.stock) > 0 ? `${product.stock} in stock` : "Unavailable"}</p><div class="product-bottom"><div><div class="price">${money(product.price)}</div><div class="mrp">${product.mrp ? money(product.mrp) : ""}</div></div>${quantity ? `<div class="stepper"><button data-minus="${product.id}">−</button><strong>${quantity}</strong><button data-plus="${product.id}" ${quantity >= Number(product.stock || 999999) ? "disabled" : ""}>+</button></div>` : `<button class="add-button" data-add="${product.id}" ${out ? "disabled" : ""}>${out ? "Sold out" : "+ ADD"}</button>`}</div></article>`; }
function filteredProducts(){ const query = state.search.trim().toLowerCase(); return state.products.filter((product) => (state.category === "all" || String(product.categoryName).toLowerCase() === state.category.toLowerCase()) && (!query || `${product.name} ${product.categoryName}`.toLowerCase().includes(query))); }
function homeView(){ const categoryButtons = [{ name:"All items", value:"all" }, ...state.categories.map((category) => ({ name:category.name, value:category.name }))]; const content = `<main><section class="hero"><div class="hero-card"><span class="hero-kicker">✦ quick basket</span><h1>The good stuff,<br><em>without the wait.</em></h1><p>Everyday groceries, fair prices, and a front door delivery in 10 minutes flat.</p><div class="hero-pills"><span class="hero-pill">⚡ 10 min delivery</span><span class="hero-pill">✓ No minimum order</span></div></div></section><section class="section" id="categories"><div class="section-head"><div><div class="eyebrow">Your neighborhood shelf</div><h2>Shop essentials</h2></div><span class="count">${filteredProducts().length} products</span></div><div class="categories">${categoryButtons.map((category) => `<button class="category-button ${state.category === category.value ? "active" : ""}" data-category="${esc(category.value)}">${esc(category.name)}</button>`).join("")}</div></section><section class="section"><div id="catalog">${state.loading ? Array.from({length:8}, () => `<div class="skeleton"></div>`).join("") : state.error ? `<div class="empty-state"><div class="empty-icon">⚠</div><h2>Something went wrong</h2><p>${esc(state.error)}</p><button class="secondary-cta" id="retry-catalog">Try again</button></div>` : filteredProducts().length ? `<div class="grid">${filteredProducts().map(productCard).join("")}</div>` : `<div class="empty-state"><div class="empty-icon">⌕</div><h2>No products found</h2><p>Try another search or category.</p></div>`}</div></section></main>${state.loading || !cartCount() ? "" : `<div class="floating-cart"><a href="cart.html"><button><span class="total-label"><small>${cartCount()} ${cartCount() === 1 ? "item" : "items"} in your cart</small><strong>View cart</strong></span><span class="view-price">${money(cartTotal())} →</span></button></a></div>`}`; document.title = "SS Store · Fresh in a flash"; return appShell(content); }
function cartView(){ const items = cartItems(); const content = `<main class="page"><a class="back-link" href="index.html">← Continue shopping</a><div class="eyebrow">Your basket</div><h1 class="page-title">Ready when you are.</h1>${items.length ? `<div class="cart-list">${items.map(({product, quantity}) => `<div class="cart-item"><div class="cart-thumb">${product.imageUrl ? `<img src="${esc(product.imageUrl)}" alt="" onerror="this.replaceWith(document.createTextNode('📦'))">` : "📦"}</div><div class="cart-item-main"><strong>${esc(product.name)}</strong><small>${esc(product.categoryName)}</small><b>${money(product.price)}</b></div><div class="cart-stepper"><button data-cart-minus="${product.id}">−</button><strong>${quantity}</strong><button data-cart-plus="${product.id}">+</button></div></div>`).join("")}</div><div class="summary"><div class="summary-row"><span>Items</span><span>${cartCount()}</span></div><div class="summary-row total"><span>Total</span><span>${money(cartTotal())}</span></div><a href="checkout.html"><button class="primary-cta">Proceed to checkout →</button></a></div>` : `<div class="empty-state"><div class="empty-icon">🛍</div><h2>Your cart is empty</h2><p>Add a few everyday essentials and we’ll get moving.</p><a href="index.html"><button class="secondary-cta">Browse products</button></a></div>`}</main>`; document.title = "SS Store · Cart"; return appShell(content); }
function checkoutView(){ const items = cartItems(); if(!items.length){ location.href = "cart.html"; return ""; } const phone = localStorage.getItem(PHONE_KEY) || ""; const content = `<main class="page"><a class="back-link" href="cart.html">← Back to cart</a><div class="eyebrow">Almost there</div><h1 class="page-title">One quick checkout.</h1><form class="form-card" id="checkout-form"><label class="field-label" for="phone">Phone number</label><input class="field" id="phone" name="phone" type="tel" inputmode="tel" autocomplete="tel" required value="${esc(phone)}" placeholder="+91 98765 43210"><label class="field-label" for="address">Delivery address</label><textarea class="field textarea" id="address" name="address" required placeholder="Flat, street, area, city"></textarea><p class="required-note">Your phone is required for order updates. The current API stores the order against your phone; address is collected for delivery context.</p><div id="checkout-error"></div><button class="primary-cta" id="place-order" type="submit">Place order · ${money(cartTotal())}</button></form><div class="status-card"><strong>⚡ Fast delivery</strong><p>Your order is packed as soon as it is accepted.</p></div></main>`; document.title = "SS Store · Checkout"; return appShell(content); }
function successView(){ let order = {}; try { order = JSON.parse(localStorage.getItem(LAST_ORDER_KEY) || "{}"); } catch {} const content = `<main class="success-wrap"><div class="success-icon">✓</div><div class="eyebrow" style="margin-top:26px">Order confirmed</div><h1>Your basket is on its way.</h1><p>Your SS Store order was accepted and is being prepared now.</p><div class="order-id">Order ID<br><strong>#${esc(order.id || "—")}</strong></div><div class="status-card" style="text-align:left"><strong>Status: ${esc(order.status || "PENDING")}</strong><p>We’ll keep your order moving.</p></div><a href="index.html"><button class="primary-cta">Continue shopping</button></a></main>`; document.title = "SS Store · Order confirmed"; return appShell(content); }
function bind(){ $("#search-input")?.addEventListener("input", (event) => { state.search = event.target.value; render(); }); $$('[data-category]').forEach((button) => button.addEventListener("click", () => { state.category = button.dataset.category; render(); document.querySelector("#categories")?.scrollIntoView({ behavior:"smooth", block:"start" }); })); $$('[data-add]').forEach((button) => button.addEventListener("click", () => changeQty(Number(button.dataset.add), 1))); $$('[data-plus]').forEach((button) => button.addEventListener("click", () => changeQty(Number(button.dataset.plus), 1))); $$('[data-minus]').forEach((button) => button.addEventListener("click", () => changeQty(Number(button.dataset.minus), -1))); $$('[data-cart-plus]').forEach((button) => button.addEventListener("click", () => changeQty(Number(button.dataset.cartPlus), 1))); $$('[data-cart-minus]').forEach((button) => button.addEventListener("click", () => changeQty(Number(button.dataset.cartMinus), -1))); $("#retry-catalog")?.addEventListener("click", fetchCatalog); $("#checkout-form")?.addEventListener("submit", submitOrder); }
function changeQty(id, delta){ const product = state.products.find((item) => Number(item.id) === id); if(!product) return; const current = Number(state.cart[id] || 0); const next = Math.max(0, current + delta); if(Number(product.stock) >= 0 && next > Number(product.stock)) return toast(`Only ${product.stock} available.`, "error"); if(next) state.cart[id] = next; else delete state.cart[id]; writeCart(); render(); }
async function submitOrder(event){ event.preventDefault(); const form = event.target; const phone = String(new FormData(form).get("phone") || "").trim(); const address = String(new FormData(form).get("address") || "").trim(); const errorNode = $("#checkout-error"); if(!phone || phone.replace(/\D/g, "").length < 7){ errorNode.innerHTML = `<div class="inline-error">Enter a valid phone number.</div>`; return; } if(!address){ errorNode.innerHTML = `<div class="inline-error">Enter a delivery address.</div>`; return; } if(!cartItems().length){ location.href = "cart.html"; return; } const button = $("#place-order"); button.disabled = true; button.textContent = "Placing order…"; errorNode.innerHTML = ""; localStorage.setItem(PHONE_KEY, phone); const idempotencyKey = `ss-${Date.now()}-${Math.random().toString(36).slice(2,10)}`; try { const order = await request("/api/orders", { method:"POST", headers:{ "Idempotency-Key":idempotencyKey }, body:JSON.stringify({ phone, items:cartItems().map(({product,quantity}) => ({ productId:product.id, quantity })) }) }); localStorage.setItem(LAST_ORDER_KEY, JSON.stringify({ ...order, status:order?.status || "PENDING" })); state.cart = {}; writeCart(); location.href = "success.html"; } catch(error){ errorNode.innerHTML = `<div class="inline-error">${esc(error.message || "Something went wrong. Try again.")}</div>`; button.disabled = false; button.textContent = `Place order · ${money(cartTotal())}`; await fetchProducts().catch(() => {}); } }
function render(){ if(page === "home") $("#app").innerHTML = homeView(); if(page === "cart") $("#app").innerHTML = cartView(); if(page === "checkout") $("#app").innerHTML = checkoutView(); if(page === "success") $("#app").innerHTML = successView(); bind(); }
render(); if(page === "home") fetchCatalog(); if(page === "cart" || page === "checkout") fetchProducts().then(() => render()).catch((error) => { state.error = error.message; render(); });
